import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@hotspot/ui/globals.css';
import { ModalProvider } from '@hotspot/ui';
import { StoreProvider } from '@/app/_providers';
import { AppModal } from '@/widgets/app-modal/ui/AppModal';
import { QueryProvider } from './_providers/query/QueryProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-dvh`}>
        <StoreProvider>
          <QueryProvider>
            <ModalProvider>
              <main className="bg-white min-h-dvh w-full">{children}</main>
              <AppModal />
            </ModalProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
