import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@hotspot/ui/globals.css';
import { ModalProvider } from '@hotspot/ui';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { AppModal } from '@/widgets/app-modal/ui/AppModal';
import { QueryProvider } from './_providers/query/QueryProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <QueryProvider>
          <ModalProvider>
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
            <AppModal />
          </ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
