import type { Metadata } from 'next';
import '@hotspot/ui/globals.css';
import { ModalProvider } from '@hotspot/ui';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { AppModal } from '@/widgets/app-modal/ui/AppModal';
import { QueryProvider } from './_providers/query/QueryProvider';

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <ModalProvider>
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
            <AppModal />
          </ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
