/** biome-ignore-all lint/correctness/noNodejsModules: <explanation> */
/** biome-ignore-all lint/style/useNodejsImportProtocol: <explanation> */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function resolveFromScript(...segments: string[]) {
  return path.resolve(__dirname, ...segments);
}

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

type FlatToken = { value: string; type: string };

// 토큰 객체를 key.path 형태로 평탄화: key -> {value, type}
function flattenTokens(obj: any, prefix = '', out: Record<string, FlatToken> = {}) {
  if (!obj || typeof obj !== 'object') return out;

  if ('$value' in obj && '$type' in obj && typeof obj.$type === 'string') {
    if (!prefix) return out;
    out[prefix] = { type: obj.$type, value: String(obj.$value) };
    return out;
  }
  for (const key of Object.keys(obj)) {
    const next = obj[key];
    const nextPrefix = prefix ? `${prefix}.${key}` : key;
    if (next && typeof next === 'object') {
      flattenTokens(next, nextPrefix, out);
    }
  }
  return out;
}

function toCSSVarName(key: string): string {
  return key.replace(/\./g, '-').toLowerCase();
}

// 시맨틱 토큰의 {ref}를 프리미티브 맵으로 해석
function resolveSemantics(
  semanticFlat: Record<string, FlatToken>,
  primitiveMap: Record<string, string>,
) {
  const resolved: Record<string, string> = {};
  for (const [key, tok] of Object.entries(semanticFlat)) {
    if (tok.type !== 'color') continue;
    let v = tok.value;

    // {a.b.c} 형태 참조 치환
    v = v.replace(/\{([^}]+)\}/g, (_, refPath) => {
      return primitiveMap[refPath] ?? `{${refPath}}`; // 못 찾으면 원문 유지
    });

    resolved[toCSSVarName(key)] = v;
  }
  return resolved;
}

// 원시 토큰 로드
const raw = loadJSON(resolveFromScript('../tokens/tokens.json'));
const primitiveLight = raw['primitive/Mode 1'] ?? {};
const semanticLight = raw['semantic/Mode 1']?.color ?? {};

// 프리미티브 평탄화
const primitiveFlatLight = flattenTokens(primitiveLight);

const primitiveMapLight: Record<string, string> = {};
for (const [k, t] of Object.entries(primitiveFlatLight)) {
  if (t.type === 'color') primitiveMapLight[k] = t.value;
}

// 시맨틱 평탄화 후 참조 해석
const semanticFlatLight = flattenTokens(semanticLight);

const lightColors = resolveSemantics(semanticFlatLight, primitiveMapLight);

const outPath = resolveFromScript('../src/styles/color-tokens.css');
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-color.ts */\n`;

// Light
cssOutput += `@theme {\n`;
Object.entries(lightColors)
  .sort(([a], [b]) => a.localeCompare(b))
  .forEach(([key, value]) => {
    cssOutput += `  --color-${key}: ${value};\n`;
  });
cssOutput += `}\n\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
