/** biome-ignore-all lint/correctness/noNodejsModules: <explanation> */
/** biome-ignore-all lint/style/useNodejsImportProtocol: <explanation> */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function resolveFromScript(...segments: string[]) {
  return path.resolve(__dirname, ...segments);
}

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function get(obj: unknown, keyPath: string) {
  return keyPath.split('.').reduce<any>((acc, key) => (acc ? acc[key] : undefined), obj);
}

const refAliases: Record<string, string> = {
  fontSize: 'typography.fontSize',
  letterSpacing: 'typography.letterSpacing',
  paragraphIndent: 'typography.paragraphIndent',
  paragraphSpacing: 'typography.paragraphSpacing',
  textCase: 'typography.textCase',
  textDecoration: 'typography.textDecoration',
  'typography.font-family': 'primitive/Mode 1.typography.font-family',
  'typography.font-weight': 'primitive/Mode 1.typography.font-weight',
  'typography.line-height': 'primitive/Mode 1.typography.line-height',
};

function normalizeRefPath(refPath: string) {
  const matchedPrefix = Object.keys(refAliases).find(
    (prefix) => refPath === prefix || refPath.startsWith(`${prefix}.`),
  );

  if (!matchedPrefix) return refPath;

  const replacement = refAliases[matchedPrefix];
  return replacement ? refPath.replace(matchedPrefix, replacement) : refPath;
}

function resolveRef(root: any, value: unknown): unknown {
  if (typeof value !== 'string') return value;

  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return value;

  const refPath = normalizeRefPath(match[1] ?? '');
  const direct = get(root, refPath);

  if (direct && typeof direct === 'object' && '$value' in direct) {
    return resolveRef(root, direct.$value);
  }

  if (direct !== undefined) {
    return direct;
  }
  return value;
}

function ensureDimension(value: unknown, fallback = '0px') {
  if (value == null) return fallback;
  if (typeof value === 'number' && Number.isFinite(value)) return `${value}px`;

  if (typeof value === 'string') {
    const normalized = value.trim();
    if (/^-?\d+(\.\d+)?(px|em|rem|%)$/.test(normalized)) return normalized;

    const numeric = Number.parseFloat(normalized);
    return Number.isFinite(numeric) ? `${numeric}px` : fallback;
  }

  return fallback;
}

function ensureLetterSpacing(value: unknown, fallback = 'normal') {
  if (value == null) return fallback;
  if (typeof value === 'number' && Number.isFinite(value)) return `${value}px`;

  if (typeof value === 'string') {
    const normalized = value.trim();
    if (normalized === 'normal') return normalized;
    if (/^-?\d+(\.\d+)?(px|em|rem|%)$/.test(normalized)) return normalized;

    const numeric = Number.parseFloat(normalized);
    return Number.isFinite(numeric) ? `${numeric}px` : fallback;
  }

  return fallback;
}

const textCaseMap: Record<string, string> = {
  lower: 'lowercase',
  none: 'none',
  original: 'none',
  title: 'capitalize',
  upper: 'uppercase',
};

const fontWeightMap: Record<string, string> = {
  black: '900',
  bold: '700',
  extrabold: '800',
  extralight: '200',
  light: '300',
  medium: '500',
  regular: '400',
  semibold: '600',
  thin: '100',
};

function toClassName(group: string, tokenName: string) {
  return `.font-${group}-${tokenName}`.toLowerCase();
}

function normalizeFontWeight(value: unknown) {
  if (typeof value === 'number') return String(value);
  if (typeof value !== 'string') return '400';

  const normalized = value.trim().toLowerCase();
  return fontWeightMap[normalized] ?? normalized;
}

const raw = loadJSON(resolveFromScript('../tokens/tokens.json'));
const typography = raw.typography ?? {};
const groups = typography.KR ?? {};

const outPath = resolveFromScript('../src/styles/typo-tokens.css');
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-typo.ts */\n@layer utilities {\n`;

for (const [groupName, groupTokens] of Object.entries<any>(groups)) {
  if (!groupTokens || typeof groupTokens !== 'object') continue;

  for (const [tokenName, token] of Object.entries<any>(groupTokens)) {
    if (!token || token.$type !== 'typography' || !token.$value) continue;

    const typographyValue = token.$value;
    const className = toClassName(groupName, tokenName);

    const fontFamily = resolveRef(raw, typographyValue.fontFamily);
    const fontSize = ensureDimension(resolveRef(raw, typographyValue.fontSize));
    const fontWeight = normalizeFontWeight(resolveRef(raw, typographyValue.fontWeight));
    const lineHeight = ensureDimension(resolveRef(raw, typographyValue.lineHeight), 'normal');
    const letterSpacing = ensureLetterSpacing(resolveRef(raw, typographyValue.letterSpacing));
    const textIndent = ensureDimension(resolveRef(raw, typographyValue.paragraphIndent));
    const paragraphSpacing = ensureDimension(resolveRef(raw, typographyValue.paragraphSpacing));
    const textCase = String(resolveRef(raw, typographyValue.textCase) ?? 'none').toLowerCase();
    const textDecoration = String(resolveRef(raw, typographyValue.textDecoration) ?? 'none');

    cssOutput += `  ${className} {\n`;
    cssOutput += `    font-family: ${fontFamily};\n`;
    cssOutput += `    font-size: ${fontSize};\n`;
    cssOutput += `    font-weight: ${fontWeight};\n`;
    cssOutput += `    line-height: ${lineHeight};\n`;
    cssOutput += `    letter-spacing: ${letterSpacing};\n`;
    cssOutput += `    text-indent: ${textIndent};\n`;
    cssOutput += `    text-transform: ${textCaseMap[textCase] ?? 'none'};\n`;
    cssOutput += `    text-decoration: ${textDecoration};\n`;
    cssOutput += `  }\n`;

    if (paragraphSpacing !== '0px') {
      cssOutput += `  ${className} + * {\n`;
      cssOutput += `    margin-top: ${paragraphSpacing};\n`;
      cssOutput += `  }\n`;
    }
  }
}

cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
