/** biome-ignore-all lint/correctness/noNodejsModules: <explanation> */
/** biome-ignore-all lint/style/useNodejsImportProtocol: <explanation> */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function resolveFromScript(...segments: string[]) {
  return path.resolve(__dirname, ...segments);
}

function loadJSON(filePath: string) {
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

function get(obj: unknown, keyPath: string) {
  return keyPath.split('.').reduce<any>((acc, key) => (acc ? acc[key] : undefined), obj);
}

function normalizeRefPath(refPath: string) {
  if (refPath === 'number' || refPath.startsWith('number.')) {
    return `primitive/Mode 1.${refPath}`;
  }

  return refPath;
}

function resolveRef(root: any, value: unknown): unknown {
  if (typeof value !== 'string') return value;

  const match = value.match(/^\{([^}]+)\}$/);
  if (!match) return value;

  const refPath = normalizeRefPath(match[1] ?? '');
  const direct = get(root, refPath);

  if (direct && typeof direct === 'object' && '$value' in direct) {
    return resolveRef(root, direct.$value);
  }

  if (direct !== undefined) {
    return direct;
  }

  return value;
}

function collectNumberScale(
  root: any,
  source: Record<string, { $type?: string; $value?: unknown }>,
): Record<string, number> {
  const entries: Record<string, number> = {};

  for (const [key, token] of Object.entries(source)) {
    if (!token || token.$type !== 'number') continue;

    const resolved = resolveRef(root, token.$value);
    const numericValue =
      typeof resolved === 'number' ? resolved : Number.parseFloat(String(resolved));

    if (Number.isFinite(numericValue)) {
      entries[key] = numericValue;
    }
  }

  return entries;
}

function toPxScale(source: Record<string, number>) {
  return Object.fromEntries(Object.entries(source).map(([key, value]) => [key, `${value}px`]));
}

const raw = loadJSON(resolveFromScript('../tokens/tokens.json'));
const system = raw['system/Mode 1'] ?? {};

const spacing = toPxScale(collectNumberScale(raw, system.spacing ?? {}));
const radius = toPxScale(collectNumberScale(raw, system.radius ?? {}));
const borderWidth = toPxScale(collectNumberScale(raw, system['border-width'] ?? {}));
const zIndex = collectNumberScale(raw, system['z-index'] ?? {});

const outPath = resolveFromScript('../src/styles/system-tokens.css');
fs.mkdirSync(path.dirname(outPath), { recursive: true });

let cssOutput = `/* auto generated by convert-system.ts */\n@theme {\n`;

for (const [key, value] of Object.entries(spacing).sort(([a], [b]) => a.localeCompare(b))) {
  cssOutput += `  --spacing-${key}: ${value};\n`;
}

for (const [key, value] of Object.entries(radius).sort(([a], [b]) => a.localeCompare(b))) {
  cssOutput += `  --radius-${key}: ${value};\n`;
}

for (const [key, value] of Object.entries(borderWidth).sort(([a], [b]) => a.localeCompare(b))) {
  cssOutput += `  --stroke-weight-${key}: ${value};\n`;
}

cssOutput += `}\n\n:root {\n`;

for (const [key, value] of Object.entries(zIndex).sort(([a], [b]) => a.localeCompare(b))) {
  cssOutput += `  --z-${key}: ${value};\n`;
}

cssOutput += `}\n\n@layer utilities {\n`;

for (const [key] of Object.entries(zIndex).sort(([a], [b]) => a.localeCompare(b))) {
  cssOutput += `  .z-${key} {\n`;
  cssOutput += `    z-index: var(--z-${key});\n`;
  cssOutput += `  }\n`;
}

cssOutput += `}\n`;

fs.writeFileSync(outPath, cssOutput, 'utf-8');
console.log(`✅ Generated ${outPath}`);
